### PR TITLE
fixing hanging issue

### PR DESCRIPTION
**Pull request by TalZaccai**

### CODE REVIEW

**Comment by jongoldDB** [comment]
Approved :)

Cheers,
Jonathan

**Comment by rrnewton** [comment]
Does "hanging" refer to PTI "job" not exiting?  It looks like it's still failing with a timeout in the same manner as before.

**Comment by darrenge** [comment]
Yes … but we need to update the release Nuget package for the fix to work.

**Comment by TalZaccai** [comment]
@rrnewton - CIs are back to health

**Pull request merged**
