### PR TITLE
Move adv-file-ops native code into managed code so there is no native dependency

### PR DESCRIPTION
**Pull request by lovettchris**
The C++ functions defined in adv-file-ops.dll have been implemented using runtime interop.  In the process I found and fixed some handle leaks that were potentially happening in error conditions.  I also did a simple command line test of the resulting CreateAndSetFileSize function, which seemed to work when running in an admin command prompt.  I also retested the hello world app after running BuildCore.cmd and it still works after erasing all copies of adv-file-ops.dll  from my hard drive.

### CODE REVIEW

**Comment by badrishc** [comment]
Hi, thanks for the PR. I actually created a newer version of Native32.cs in the [FASTER](https://github.com/microsoft/FASTER) project, which which we share several low level functionality.

This new version no longer depends on C++ adv-file-ops and is available here: https://github.com/microsoft/FASTER/blob/master/cs/src/core/Utilities/Native32.cs

We were planning to move this over to Ambrosia. It would be good to use the same code across the two systems. So let's compare and create the best of both ports.

**Comment by lovettchris** [comment]
ok, thanks, we should compare solutions then, I think your version is a literal port, mine fixes a few potential handle leaks.  For example, in EnableProcessPrivileges OpenProcessToken could succeed, resulting in a token handle, but if AdjustTokenPrivileges fails then the token is not closed.  Didn't know about the (void*) trick used in EnableVolumePrivileges - that's cool.  MakeHRFromErrorCode can be replaced with Marshal.GetHRForLastWin32Error().  My version also writes errors to Console.Error.WriteLine - similar to what the C++ code was doint on std::errr.

**Comment by lovettchris** [comment]
I merged your native32.cs from FASTER and added a couple tiny handle leak bug fixes in the error handling cases.

**Comment by badrishc** [comment]
Looks great, thanks!

**Comment by lovettchris** [comment]
The Ambrosia build was broken, I added back some missing functions like CreateIoCompletionPort and switched some things to use SafeFileHandle.

**Pull request merged**
